name: Deliver
# privileged workflow that is restricted to master & next
# in order to correspond to @latest and @next

on:
  workflow_run:
    workflows: [ Branch Update ]
    types: [ completed ]
    branches: [ master, next ]

jobs:

  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: 
      name: production
      url: https://www.npmjs.com/package/jest-serial-runner
    runs-on: ubuntu-latest
    steps:
      - name: git checkout HEAD
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install --prefer-offline --no-fund --no-audit

      - name: Clean package.json
        run: |
          npm pkg delete scripts
          npm pkg delete devDependencies
          npm pkg delete config

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
